#!/bin/bash
hostname tomcat-server
sudo amazon-linux-extras install java-openjdk11 -y
sudo yum install git wget -y
sudo mkdir /tomcat
cd tomcat
sudo wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
sudo tar -xvzf /tomcat/apache-tomcat-9.0.70.tar.gz
sudo mv /tomcat/apache-tomcat-9.0.70 /tomcat/apache-tomcat-9

sudo chmod +x /tomcat/apache-tomcat-9/bin/startup.sh 
sudo chmod +x /tomcat/apache-tomcat-9/bin/shutdown.sh

sudo ln -s /tomcat/apache-tomcat-9/bin/startup.sh /usr/local/bin/tomcatup
sudo ln -s /tomcat/apache-tomcat-9/bin/shutdown.sh /usr/local/bin/tomcatdown
tomcatup

sudo yum update -y 




###########ADDITIONAL TASK TO BE DONE##########

access tomcat application from browser on port 8080

http://<Public_IP>:8080
Using unique ports for each application is a best practice in an environment. But tomcat and Jenkins runs on ports number 8080. Hence lets change tomcat port number to 8090. Change port number in conf/server.xml file under tomcat home

cd /tomcat/apache-tomcat-9/conf


# update port number in the "connecter port" field in server.xml
# restart tomcat after configuration update

tomcatdown
tomcatup


Check point :
Access tomcat application from browser on port 8090

http://<Public_IP>:8090
now application is accessible on port 8090. but tomcat application doesnt allow to login from browser. changing a default parameter in context.xml does address this issue
#search for context.xml
find / -name context.xml
above command gives 3 context.xml files. comment () Value ClassName field on files which are under webapp directory. After that restart tomcat services to effect these changes. At the time of writing this lecture below 2 files are updated.
/opt/tomcat/webapps/host-manager/META-INF/context.xml
/opt/tomcat/webapps/manager/META-INF/context.xml

# Restart tomcat services
tomcatdown  
tomcatup
Update users information in the tomcat-users.xml file goto tomcat home directory and Add below users to conf/tomcat-users.xml file
 <role rolename="manager-gui"/>
 <role rolename="manager-script"/>
 <role rolename="manager-jmx"/>
 <role rolename="manager-status"/>
 <user username="admin" password="admin" roles="manager-gui, manager-script, manager-jmx, manager-status"/>
 <user username="deployer" password="deployer" roles="manager-script"/>
 <user username="tomcat" password="micr0degree" roles="manager-gui"/>
Restart serivce and try to login to tomcat application from the browser. This time it should be Successful

